<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PengurusJabatansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pengurus_jabatans')->delete();
        
        \DB::table('pengurus_jabatans')->insert(array (
            0 => 
            array (
                'id' => '1',
                'no_urut' => '4',
                'nama' => 'Komunikasi dan Informasi',
                'slug' => '2021-2022-komunikasi-dan-informasi',
                'foto' => '2021-12-04_09-58-12_karmapack_image_Kominfo.png',
                'singkatan' => 'KOMINFO',
                'visi' => NULL,
                'misi' => NULL,
                'slogan' => 'Bersama Kominfo Karmapack Mengudara',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            1 => 
            array (
                'id' => '3',
                'no_urut' => '1',
                'nama' => 'Ketua Umum',
                'slug' => '2021-2022-ketua-umum',
                'foto' => 'iconketua-umum20220425133058.png',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>',
                'misi' => '<p>misi</p>',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            2 => 
            array (
                'id' => '7',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2021-2022-komunikasi-dan-informasi-anggota',
                'foto' => '2021-12-04_10-23-11_karmapack_image_Anggota.png',
                'singkatan' => NULL,
                'visi' => 'visi',
                'misi' => 'misi',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '1',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            3 => 
            array (
                'id' => '8',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2021-2022-komunikasi-dan-informasi-ketua-bidang',
                'foto' => '2021-12-04_10-23-27_karmapack_image_Ketua.png',
                'singkatan' => NULL,
                'visi' => '<p>visia</p>',
                'misi' => '<p>misia</p>',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '1',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            4 => 
            array (
                'id' => '9',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2021-2022-komunikasi-dan-informasi-sekertaris-bidang',
                'foto' => '2021-12-04_10-23-52_karmapack_image_Sekertaris-bidang.png',
                'singkatan' => NULL,
                'visi' => 'visi',
                'misi' => 'misi',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '1',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            5 => 
            array (
                'id' => '10',
                'no_urut' => '5',
                'nama' => 'Wirausaha',
                'slug' => '2021-2022-wirausaha',
                'foto' => '2021-12-04_10-25-19_karmapack_image_Wira_Usaha.png',
                'singkatan' => NULL,
                'visi' => 'visi',
                'misi' => 'misi',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            6 => 
            array (
                'id' => '11',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2021-2022-wira-usaha-ketua-bidang',
                'foto' => '2021-12-04_10-25-47_karmapack_image_Ketua.png',
                'singkatan' => NULL,
                'visi' => 'visi',
                'misi' => 'misi',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '10',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            7 => 
            array (
                'id' => '12',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2021-2022-wira-usaha-sekertaris-bidang',
                'foto' => '2021-12-04_10-26-00_karmapack_image_Sekertaris.png',
                'singkatan' => NULL,
                'visi' => 'visi',
                'misi' => 'misi',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '10',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            8 => 
            array (
                'id' => '13',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2021-2022-wira-usaha-anggota',
                'foto' => '2021-12-04_10-26-10_karmapack_image_Anggota.png',
                'singkatan' => NULL,
                'visi' => 'visi',
                'misi' => 'misi',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '10',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            9 => 
            array (
                'id' => '14',
                'no_urut' => '6',
                'nama' => 'Nalar dan Intelektual',
                'slug' => '2021-2022-nalar-dan-intelektual',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>Visi Indonesia raya merdeka</p>',
                'misi' => '<p>Misi Indonesia raya merdeka</p>',
                'slogan' => 'Hebat Tamat',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            10 => 
            array (
                'id' => '15',
                'no_urut' => '7',
                'nama' => 'Minat dan Bakat',
                'slug' => '2021-2022-minat-dan-bakat',
                'foto' => '2021-12-07_09-07-24_karmapack_image_Minat_Dan_Bakat.jpg',
                'singkatan' => 'MIBA',
                'visi' => '<p>Visi</p>',
                'misi' => '<p>Misi</p>',
                'slogan' => 'Slogan',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            11 => 
            array (
                'id' => '17',
                'no_urut' => '2',
                'nama' => 'Sekertaris Umum',
                'slug' => '2021-2022-sekertaris-umum',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '-',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            12 => 
            array (
                'id' => '18',
                'no_urut' => '3',
                'nama' => 'Bendahara Umum',
                'slug' => '2021-2022-bendahara-umum',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '-',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            13 => 
            array (
                'id' => '19',
                'no_urut' => '8',
                'nama' => 'Pengembangan Aparatur Organisasi',
                'slug' => '2021-2022-pengembangan-aparatur-organisasi',
                'foto' => '',
                'singkatan' => 'PAO',
                'visi' => '<p>-</p>',
                'misi' => '<p>-</p>',
                'slogan' => '-',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            14 => 
            array (
                'id' => '20',
                'no_urut' => '9',
                'nama' => 'Pengembangan Kode Etik dan Akhlakul Karimah',
                'slug' => '2021-2022-pengembangan-kode-etik-dan-akhlakul-karimah',
                'foto' => '',
                'singkatan' => 'PAKEAK',
                'visi' => '<p>-</p>',
                'misi' => '<p>-</p>',
                'slogan' => '-',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            15 => 
            array (
                'id' => '21',
                'no_urut' => '10',
                'nama' => 'Sosial Masyarakat',
                'slug' => '2021-2022-sosial-masyarakat',
                'foto' => '',
                'singkatan' => 'SOSMAS',
                'visi' => '<p>-</p>',
                'misi' => '<p>-</p>',
                'slogan' => '-',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            16 => 
            array (
                'id' => '22',
                'no_urut' => '11',
                'nama' => 'Keperempuanan',
                'slug' => '2021-2022-keperempuanan',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>-</p>',
                'misi' => '<p>-</p>',
                'slogan' => '-',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            17 => 
            array (
                'id' => '23',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2021-2022-nalar-dan-intelektual-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '14',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            18 => 
            array (
                'id' => '24',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2021-2022-nalar-dan-intelektual-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '14',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            19 => 
            array (
                'id' => '25',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2021-2022-nalar-dan-intelektual-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '14',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            20 => 
            array (
                'id' => '26',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2021-2022-minat-dan-bakat-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '15',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            21 => 
            array (
                'id' => '27',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2021-2022-minat-dan-bakat-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '15',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            22 => 
            array (
                'id' => '28',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2021-2022-minat-dan-bakat-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '15',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            23 => 
            array (
                'id' => '29',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2021-2022-pengembangan-aparatur-organisasi-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '19',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            24 => 
            array (
                'id' => '30',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2021-2022-pengembangan-aparatur-organisasi-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '19',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            25 => 
            array (
                'id' => '31',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2021-2022-pengembangan-aparatur-organisasi-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '19',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            26 => 
            array (
                'id' => '32',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2021-2022-pengembangan-kode-etik-dan-akhlakul-karimah-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '20',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            27 => 
            array (
                'id' => '33',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2021-2022-pengembangan-kode-etik-dan-akhlakul-karimah-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '20',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            28 => 
            array (
                'id' => '34',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2021-2022-pengembangan-kode-etik-dan-akhlakul-karimah-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '20',
                'created_at' => '2023-02-11 02:06:13',
                'updated_at' => '2023-02-11 02:06:13',
            ),
            29 => 
            array (
                'id' => '35',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2021-2022-sosial-masyarakat-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '21',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            30 => 
            array (
                'id' => '36',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2021-2022-sosial-masyarakat-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '21',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            31 => 
            array (
                'id' => '37',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2021-2022-sosial-masyarakat-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '21',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            32 => 
            array (
                'id' => '38',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2021-2022-keperempuanan-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '22',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            33 => 
            array (
                'id' => '39',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2021-2022-keperempuanan-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '',
                'misi' => '',
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '22',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            34 => 
            array (
                'id' => '40',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2021-2022-keperempuanan-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>-</p>',
                'misi' => '<p>-</p>',
                'slogan' => '-',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '1',
                'parent_id' => '22',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            35 => 
            array (
                'id' => '41',
                'no_urut' => '1',
                'nama' => 'Ketua Umum',
                'slug' => '2022-2023-ketua-umum',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '4',
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            36 => 
            array (
                'id' => '42',
                'no_urut' => '2',
                'nama' => 'Sekertaris Umum',
                'slug' => '2022-2023-sekertaris-umum',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '5',
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            37 => 
            array (
                'id' => '43',
                'no_urut' => '3',
                'nama' => 'Bendahara Umum',
                'slug' => '2022-2023-bendahara-umum',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '6',
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            38 => 
            array (
                'id' => '44',
                'no_urut' => '9',
                'nama' => 'Komunikasi dan Informasi',
                'slug' => '2022-2023-komunikasi-dan-informasi',
                'foto' => '',
                'singkatan' => 'KOMINFO',
                'visi' => '<p>-</p>
',
                'misi' => '<p>-</p>
',
                'slogan' => 'Bersama Kominfo Karmapack Mengudara',
                'status' => '1',
                'role_id' => '1',
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            39 => 
            array (
                'id' => '45',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2022-2023-komunikasi-dan-informasi-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visia</p>
',
                'misi' => '<p>misia</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '1',
                'periode_id' => '2',
                'parent_id' => '44',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            40 => 
            array (
                'id' => '46',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2022-2023-komunikasi-dan-informasi-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '1',
                'periode_id' => '2',
                'parent_id' => '44',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            41 => 
            array (
                'id' => '47',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2022-2023-komunikasi-dan-informasi-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '1',
                'periode_id' => '2',
                'parent_id' => '44',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            42 => 
            array (
                'id' => '52',
                'no_urut' => '6',
                'nama' => 'Pengembangan Nalar dan Intelektual',
                'slug' => '2022-2023-pengembangan-nalar-dan-intelektual',
                'foto' => '',
                'singkatan' => 'PNI',
                'visi' => '<p>-</p>
',
                'misi' => '<p>-</p>
',
                'slogan' => '-',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            43 => 
            array (
                'id' => '53',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2022-2023-pengembangan-nalar-dan-intelektual-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visia</p>
',
                'misi' => '<p>misia</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '7',
                'periode_id' => '2',
                'parent_id' => '52',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            44 => 
            array (
                'id' => '54',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2022-2023-pengembangan-nalar-dan-intelektual-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '8',
                'periode_id' => '2',
                'parent_id' => '52',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            45 => 
            array (
                'id' => '56',
                'no_urut' => '8',
                'nama' => 'Minat dan Bakat',
                'slug' => '2022-2023-minat-dan-bakat',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>-</p>
',
                'misi' => '<p>-</p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '1',
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            46 => 
            array (
                'id' => '57',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2022-2023-minat-dan-bakat-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visia</p>
',
                'misi' => '<p>misia</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '7',
                'periode_id' => '2',
                'parent_id' => '56',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            47 => 
            array (
                'id' => '58',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2022-2023-minat-dan-bakat-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '8',
                'periode_id' => '2',
                'parent_id' => '56',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            48 => 
            array (
                'id' => '59',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2022-2023-minat-dan-bakat-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '3',
                'periode_id' => '2',
                'parent_id' => '56',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            49 => 
            array (
                'id' => '60',
                'no_urut' => '4',
                'nama' => 'Pengembangan Aparatur Organisasi',
                'slug' => '2022-2023-pengembangan-aparatur-organisasi',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>-</p>
',
                'misi' => '<p>-</p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '1',
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            50 => 
            array (
                'id' => '61',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2022-2023-pengembangan-aparatur-organisasi-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visia</p>
',
                'misi' => '<p>misia</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '7',
                'periode_id' => '2',
                'parent_id' => '60',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            51 => 
            array (
                'id' => '62',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2022-2023-pengembangan-aparatur-organisasi-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '8',
                'periode_id' => '2',
                'parent_id' => '60',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            52 => 
            array (
                'id' => '63',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2022-2023-pengembangan-aparatur-organisasi-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '3',
                'periode_id' => '2',
                'parent_id' => '60',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            53 => 
            array (
                'id' => '64',
                'no_urut' => '5',
                'nama' => 'Pengembangan Kode Etik dan Akhlakul Karimah',
                'slug' => '2022-2023-pengembangan-kode-etik-dan-akhlakul-karimah',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>-</p>
',
                'misi' => '<p>-</p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '1',
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            54 => 
            array (
                'id' => '65',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2022-2023-pengembangan-kode-etik-dan-akhlakul-karimah-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visia</p>
',
                'misi' => '<p>misia</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '7',
                'periode_id' => '2',
                'parent_id' => '64',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            55 => 
            array (
                'id' => '66',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2022-2023-pengembangan-kode-etik-dan-akhlakul-karimah-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '8',
                'periode_id' => '2',
                'parent_id' => '64',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            56 => 
            array (
                'id' => '67',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2022-2023-pengembangan-kode-etik-dan-akhlakul-karimah-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '3',
                'periode_id' => '2',
                'parent_id' => '64',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            57 => 
            array (
                'id' => '68',
                'no_urut' => '10',
                'nama' => '	Sosial Masyarakat',
                'slug' => '2022-2023-sosial-masyarakat',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => NULL,
                'misi' => NULL,
                'slogan' => '',
                'status' => '1',
                'role_id' => NULL,
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            58 => 
            array (
                'id' => '69',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2022-2023-sosial-masyarakat-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visia</p>
',
                'misi' => '<p>misia</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '7',
                'periode_id' => '2',
                'parent_id' => '68',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            59 => 
            array (
                'id' => '70',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2022-2023-sosial-masyarakat-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '8',
                'periode_id' => '2',
                'parent_id' => '68',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            60 => 
            array (
                'id' => '72',
                'no_urut' => '7',
                'nama' => 'Keperempuanan',
                'slug' => '2022-2023-keperempuanan',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>-</p>
',
                'misi' => '<p>-</p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '1',
                'periode_id' => '2',
                'parent_id' => NULL,
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            61 => 
            array (
                'id' => '73',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2022-2023-keperempuanan-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visia</p>
',
                'misi' => '<p>misia</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '7',
                'periode_id' => '2',
                'parent_id' => '72',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            62 => 
            array (
                'id' => '74',
                'no_urut' => '2',
                'nama' => 'Sekertaris bidang',
                'slug' => '2022-2023-keperempuanan-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '8',
                'periode_id' => '2',
                'parent_id' => '72',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            63 => 
            array (
                'id' => '75',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2022-2023-keperempuanan-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>visi</p>
',
                'misi' => '<p>misi</p>
',
                'slogan' => 'Hebat',
                'status' => '1',
                'role_id' => '3',
                'periode_id' => '2',
                'parent_id' => '72',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            64 => 
            array (
                'id' => '76',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2022-2023-pengembangan-nalar-dan-intelektual-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>-</p>
',
                'misi' => '<p>-</p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '3',
                'periode_id' => '2',
                'parent_id' => '52',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            65 => 
            array (
                'id' => '77',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2022-2023-sosial-masyarakat-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p>-</p>
',
                'misi' => '<p>-</p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '3',
                'periode_id' => '2',
                'parent_id' => '68',
                'created_at' => '2023-02-11 02:06:14',
                'updated_at' => '2023-02-11 02:06:14',
            ),
            66 => 
            array (
                'id' => '78',
                'no_urut' => '1',
                'nama' => 'Ketua Umum',
                'slug' => '2003-2003-ketua-umum',
                'foto' => 'iconketua-umum20230218203820.jpg',
                'singkatan' => NULL,
                'visi' => '<p></p>
',
                'misi' => '<p></p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '4',
                'periode_id' => NULL,
                'parent_id' => NULL,
                'created_at' => '2023-02-18 20:36:36',
                'updated_at' => '2023-02-18 20:38:20',
            ),
            67 => 
            array (
                'id' => '83',
                'no_urut' => '2',
                'nama' => 'Komunikasi dan inoformasi',
                'slug' => '2003-2003-komunikasi-dan-inoformasi',
                'foto' => 'iconkomunikasi-dan-inoformasi20230218205423.jpg',
                'singkatan' => 'kominfo',
                'visi' => '<p>v</p>
',
                'misi' => '<p>v</p>
',
                'slogan' => 'slogan',
                'status' => '1',
                'role_id' => '2',
                'periode_id' => NULL,
                'parent_id' => NULL,
                'created_at' => '2023-02-18 20:54:23',
                'updated_at' => '2023-02-18 20:54:23',
            ),
            68 => 
            array (
                'id' => '84',
                'no_urut' => '1',
                'nama' => 'Ketua Bidang',
                'slug' => '2003-2003-komunikasi-dan-inoformasi-ketua-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p></p>
',
                'misi' => '<p></p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '2',
                'periode_id' => NULL,
                'parent_id' => '83',
                'created_at' => '2023-02-18 20:54:38',
                'updated_at' => '2023-02-18 20:54:38',
            ),
            69 => 
            array (
                'id' => '85',
                'no_urut' => '2',
                'nama' => 'Sekertaris Bidang',
                'slug' => '2003-2003-komunikasi-dan-inoformasi-sekertaris-bidang',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p></p>
',
                'misi' => '<p></p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '2',
                'periode_id' => NULL,
                'parent_id' => '83',
                'created_at' => '2023-02-18 20:54:54',
                'updated_at' => '2023-02-18 20:54:54',
            ),
            70 => 
            array (
                'id' => '86',
                'no_urut' => '3',
                'nama' => 'Anggota',
                'slug' => '2003-2003-komunikasi-dan-inoformasi-anggota',
                'foto' => '',
                'singkatan' => NULL,
                'visi' => '<p></p>
',
                'misi' => '<p></p>
',
                'slogan' => NULL,
                'status' => '1',
                'role_id' => '2',
                'periode_id' => NULL,
                'parent_id' => '83',
                'created_at' => '2023-02-18 20:55:08',
                'updated_at' => '2023-02-18 20:55:08',
            ),
        ));
        
        
    }
}