<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PMenuTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('p_menu')->delete();
        
        \DB::table('p_menu')->insert(array (
            0 => 
            array (
                'id' => '345',
                'parent_id' => NULL,
                'title' => 'Admin Dashboard',
                'icon' => 'fas fa-tachometer-alt',
                'route' => 'admin.dashboard',
                'sequence' => '2',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            1 => 
            array (
                'id' => '346',
                'parent_id' => NULL,
                'title' => 'Anggota',
                'icon' => 'fas fa-users',
                'route' => 'admin.anggota',
                'sequence' => '21',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-18 00:24:07',
            ),
            2 => 
            array (
                'id' => '347',
                'parent_id' => NULL,
                'title' => 'Data Tambahan Profil',
                'icon' => 'fas fa-user',
                'route' => NULL,
                'sequence' => '22',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-18 12:53:50',
            ),
            3 => 
            array (
                'id' => '348',
                'parent_id' => '347',
                'title' => 'Jenis Pendidikan',
                'icon' => NULL,
                'route' => 'admin.profile.pendidikan_jenis',
                'sequence' => '23',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-18 12:54:26',
            ),
            4 => 
            array (
                'id' => '349',
                'parent_id' => '347',
                'title' => 'Jenis Kontak',
                'icon' => NULL,
                'route' => 'admin.profile.kontak_tipe',
                'sequence' => '24',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-18 12:54:39',
            ),
            5 => 
            array (
                'id' => '350',
                'parent_id' => NULL,
                'title' => 'Kepengurusan',
                'icon' => 'fas fa-sitemap',
                'route' => 'admin.kepengurusan.periode',
                'sequence' => '20',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-18 21:46:15',
            ),
            6 => 
            array (
                'id' => '351',
                'parent_id' => NULL,
                'title' => 'Artikel',
                'icon' => 'fas fa-file-alt',
                'route' => NULL,
                'sequence' => '4',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            7 => 
            array (
                'id' => '352',
                'parent_id' => '351',
                'title' => 'Daftar Artikel',
                'icon' => NULL,
                'route' => 'admin.artikel.data',
                'sequence' => '5',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-19 21:45:36',
            ),
            8 => 
            array (
                'id' => '353',
                'parent_id' => '351',
                'title' => 'Artikel Kategori',
                'icon' => NULL,
                'route' => 'admin.artikel.kategori',
                'sequence' => '6',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-19 21:45:45',
            ),
            9 => 
            array (
                'id' => '354',
                'parent_id' => '351',
                'title' => 'Artikel Tag',
                'icon' => NULL,
                'route' => 'admin.artikel.tag',
                'sequence' => '7',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-19 21:45:55',
            ),
            10 => 
            array (
                'id' => '355',
                'parent_id' => NULL,
                'title' => 'Data Alamat Profil',
                'icon' => 'fas fa-map-marker-alt',
                'route' => NULL,
                'sequence' => '30',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            11 => 
            array (
                'id' => '356',
                'parent_id' => '355',
                'title' => 'Provinsi',
                'icon' => NULL,
                'route' => 'admin.address.province',
                'sequence' => '31',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            12 => 
            array (
                'id' => '357',
                'parent_id' => '355',
                'title' => 'Kabupaten/Kota',
                'icon' => NULL,
                'route' => 'admin.address.regencie',
                'sequence' => '32',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            13 => 
            array (
                'id' => '358',
                'parent_id' => '355',
                'title' => 'Kecamatan',
                'icon' => NULL,
                'route' => 'admin.address.district',
                'sequence' => '33',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            14 => 
            array (
                'id' => '359',
                'parent_id' => '355',
                'title' => 'Desa/Keluarahan',
                'icon' => NULL,
                'route' => 'admin.address.village',
                'sequence' => '34',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            15 => 
            array (
                'id' => '360',
                'parent_id' => NULL,
                'title' => 'Galeri',
                'icon' => 'fas fa-images',
                'route' => 'admin.galeri',
                'sequence' => '13',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            16 => 
            array (
                'id' => '361',
                'parent_id' => NULL,
                'title' => 'Menu Management',
                'icon' => 'fas fa-stream',
                'route' => NULL,
                'sequence' => '38',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            17 => 
            array (
                'id' => '362',
                'parent_id' => NULL,
                'title' => 'Pendaftaran',
                'icon' => 'fas fa-user-edit',
                'route' => NULL,
                'sequence' => '8',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            18 => 
            array (
                'id' => '363',
                'parent_id' => NULL,
                'title' => 'Sosial Media',
                'icon' => 'fas fa-share-alt',
                'route' => 'admin.social_media',
                'sequence' => '14',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            19 => 
            array (
                'id' => '364',
                'parent_id' => NULL,
                'title' => 'Kontak',
                'icon' => 'fas fa-phone',
                'route' => NULL,
                'sequence' => '15',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            20 => 
            array (
                'id' => '365',
                'parent_id' => NULL,
                'title' => 'Instagram',
                'icon' => 'fas fa-image',
                'route' => 'admin.instagram',
                'sequence' => '12',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-02-19 22:46:23',
            ),
            21 => 
            array (
                'id' => '366',
                'parent_id' => '347',
                'title' => 'Pengaturan Nama Profil',
                'icon' => 'fas fa-check',
                'route' => 'admin.username_validation',
                'sequence' => '25',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-03-08 12:49:41',
            ),
            22 => 
            array (
                'id' => '367',
                'parent_id' => NULL,
                'title' => 'Akses Pengguna',
                'icon' => 'fas fa-user-check',
                'route' => NULL,
                'sequence' => '35',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            23 => 
            array (
                'id' => '368',
                'parent_id' => '367',
                'title' => 'Perizinan',
                'icon' => NULL,
                'route' => 'admin.user_access.permission',
                'sequence' => '36',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            24 => 
            array (
                'id' => '369',
                'parent_id' => '367',
                'title' => 'Sebagai',
                'icon' => NULL,
                'route' => 'admin.user_access.role',
                'sequence' => '37',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            25 => 
            array (
                'id' => '370',
                'parent_id' => NULL,
                'title' => 'Anggota',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '53',
                'active' => '1',
                'type' => '0',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            26 => 
            array (
                'id' => '372',
                'parent_id' => NULL,
                'title' => 'Profile',
                'icon' => 'fas fa-user',
                'route' => 'member.profile',
                'sequence' => '54',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            27 => 
            array (
                'id' => '373',
                'parent_id' => NULL,
                'title' => 'Ganti Password',
                'icon' => 'fas fa-key',
                'route' => 'member.password',
                'sequence' => '57',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            28 => 
            array (
                'id' => '386',
                'parent_id' => NULL,
                'title' => 'Logout',
                'icon' => 'fas fa-sign-out-alt',
                'route' => 'logout',
                'sequence' => '58',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:54:09',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            29 => 
            array (
                'id' => '387',
                'parent_id' => '362',
                'title' => 'List Data',
                'icon' => NULL,
                'route' => 'admin.pendaftaran',
                'sequence' => '9',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-06 00:05:47',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            30 => 
            array (
                'id' => '388',
                'parent_id' => '362',
                'title' => 'Sensus Anggota',
                'icon' => NULL,
                'route' => 'admin.pendaftaran.sensus',
                'sequence' => '11',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-06 00:06:23',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            31 => 
            array (
                'id' => '389',
                'parent_id' => NULL,
                'title' => 'Alumni Menu',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '55',
                'active' => '1',
                'type' => '0',
                'created_at' => '2022-08-06 14:06:05',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            32 => 
            array (
                'id' => '390',
                'parent_id' => NULL,
                'title' => 'Halaman Utama',
                'icon' => 'fas fa-tachometer-alt',
                'route' => 'member.dashboard',
                'sequence' => '1',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-06 15:16:19',
                'updated_at' => '2023-02-19 20:38:03',
            ),
            33 => 
            array (
                'id' => '392',
                'parent_id' => '362',
                'title' => 'Google Forms',
                'icon' => NULL,
                'route' => 'admin.pendaftaran.gform',
                'sequence' => '10',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-08 16:14:54',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            34 => 
            array (
                'id' => '393',
                'parent_id' => NULL,
                'title' => 'Utility',
                'icon' => 'fas fa-tools',
                'route' => NULL,
                'sequence' => '41',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-08 22:41:26',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            35 => 
            array (
                'id' => '394',
                'parent_id' => '393',
                'title' => 'Notifikasi Depan Atas',
                'icon' => NULL,
                'route' => 'admin.utility.notif_depan_atas',
                'sequence' => '43',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-08 22:41:53',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            36 => 
            array (
                'id' => '395',
                'parent_id' => NULL,
                'title' => 'Daftar Kata Alumni',
                'icon' => 'fas fa-user-edit',
                'route' => 'admin.kata_alumni',
                'sequence' => '50',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-09 15:20:36',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            37 => 
            array (
                'id' => '396',
                'parent_id' => NULL,
                'title' => 'Kata Alumni',
                'icon' => 'fas fa-user-edit',
                'route' => 'member.kata_alumni',
                'sequence' => '56',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-09 15:23:52',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            38 => 
            array (
                'id' => '397',
                'parent_id' => NULL,
                'title' => 'Setting Halaman',
                'icon' => 'fas fa-wrench',
                'route' => NULL,
                'sequence' => '45',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-14 21:10:57',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            39 => 
            array (
                'id' => '398',
                'parent_id' => '397',
                'title' => 'Halaman Admin',
                'icon' => NULL,
                'route' => 'admin.setting.admin',
                'sequence' => '46',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-14 21:11:42',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            40 => 
            array (
                'id' => '399',
                'parent_id' => '397',
                'title' => 'Halaman Depan',
                'icon' => NULL,
                'route' => 'admin.setting.front',
                'sequence' => '47',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-14 21:52:45',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            41 => 
            array (
                'id' => '400',
                'parent_id' => '397',
                'title' => 'Halaman Utama',
                'icon' => NULL,
                'route' => 'admin.setting.home',
                'sequence' => '48',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-16 14:55:41',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            42 => 
            array (
                'id' => '401',
                'parent_id' => '393',
                'title' => 'Hari Besar Nasional',
                'icon' => NULL,
                'route' => 'admin.utility.hari_besar_nasional',
                'sequence' => '44',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-17 21:19:05',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            43 => 
            array (
                'id' => '402',
                'parent_id' => '393',
                'title' => 'Notifikasi Admin Atas',
                'icon' => NULL,
                'route' => 'admin.utility.notif_admin_atas',
                'sequence' => '42',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-18 16:42:00',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            44 => 
            array (
                'id' => '403',
                'parent_id' => NULL,
                'title' => 'Laporan',
                'icon' => 'fas fa-book',
                'route' => NULL,
                'sequence' => '51',
                'active' => '0',
                'type' => '1',
                'created_at' => '2022-08-18 18:54:07',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            45 => 
            array (
                'id' => '404',
                'parent_id' => '403',
                'title' => 'Anggota',
                'icon' => NULL,
                'route' => 'admin.lapooran.anggota',
                'sequence' => '52',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-18 18:55:08',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            46 => 
            array (
                'id' => '405',
                'parent_id' => '361',
                'title' => 'Admin',
                'icon' => NULL,
                'route' => 'admin.menu.admin',
                'sequence' => '39',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-20 14:12:45',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            47 => 
            array (
                'id' => '406',
                'parent_id' => '361',
                'title' => 'Depan',
                'icon' => NULL,
                'route' => 'admin.menu.frontend',
                'sequence' => '40',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-20 14:16:07',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            48 => 
            array (
                'id' => '407',
                'parent_id' => '364',
                'title' => 'Pesan Diterima',
                'icon' => NULL,
                'route' => 'admin.kontak.message',
                'sequence' => '16',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-21 08:38:20',
                'updated_at' => '2023-02-19 20:35:44',
            ),
            49 => 
            array (
                'id' => '408',
                'parent_id' => '364',
                'title' => 'FAQ',
                'icon' => NULL,
                'route' => 'admin.kontak.faq',
                'sequence' => '18',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-21 08:39:18',
                'updated_at' => '2023-02-19 20:36:03',
            ),
            50 => 
            array (
                'id' => '409',
                'parent_id' => '364',
                'title' => 'Daftar Kontak',
                'icon' => NULL,
                'route' => 'admin.kontak.list',
                'sequence' => '17',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-21 08:40:08',
                'updated_at' => '2023-02-19 20:36:03',
            ),
            51 => 
            array (
                'id' => '410',
                'parent_id' => NULL,
                'title' => 'Media dan informasi',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '3',
                'active' => '1',
                'type' => '0',
                'created_at' => '2022-09-01 18:18:20',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            52 => 
            array (
                'id' => '411',
                'parent_id' => NULL,
                'title' => 'Peralatan',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '19',
                'active' => '1',
                'type' => '0',
                'created_at' => '2022-09-01 18:22:47',
                'updated_at' => '2022-09-01 18:25:56',
            ),
            53 => 
            array (
                'id' => '412',
                'parent_id' => '397',
                'title' => 'Halaman Sejarah',
                'icon' => NULL,
                'route' => 'admin.setting.sejarah',
                'sequence' => '49',
                'active' => '1',
                'type' => '1',
                'created_at' => '2023-02-19 10:02:10',
                'updated_at' => '2023-05-09 14:18:58',
            ),
            54 => 
            array (
                'id' => '413',
                'parent_id' => NULL,
                'title' => 'Seleksi Calon Ketua Umum',
                'icon' => 'fas fa-id-card',
                'route' => NULL,
                'sequence' => '26',
                'active' => '0',
                'type' => '1',
                'created_at' => '2023-05-09 11:53:00',
                'updated_at' => '2023-09-06 19:31:37',
            ),
            55 => 
            array (
                'id' => '414',
                'parent_id' => '413',
                'title' => 'Kriteria',
                'icon' => NULL,
                'route' => 'admin.spk.ahp.kriteria',
                'sequence' => '27',
                'active' => '1',
                'type' => '1',
                'created_at' => '2023-05-09 11:54:34',
                'updated_at' => '2023-05-10 02:11:00',
            ),
            56 => 
            array (
                'id' => '415',
                'parent_id' => '413',
                'title' => 'Kandidat',
                'icon' => NULL,
                'route' => 'admin.spk.ahp.alternatif',
                'sequence' => '28',
                'active' => '1',
                'type' => '1',
                'created_at' => '2023-05-09 14:17:57',
                'updated_at' => '2023-05-09 18:00:21',
            ),
            57 => 
            array (
                'id' => '416',
                'parent_id' => '413',
                'title' => 'Hasil',
                'icon' => NULL,
                'route' => 'admin.spk.ahp.perhitungan',
                'sequence' => '29',
                'active' => '1',
                'type' => '1',
                'created_at' => '2023-05-09 14:18:10',
                'updated_at' => '2023-05-09 20:56:34',
            ),
        ));
        
        
    }
}